### ISSUE TITLE
Unable to pip install shazamio on macos.

### ISSUE THREAD

**Issue by therc01** [davidAlgis/mp3ShazamAutoTag#5]
getting this

Collecting shazamio-core<2.0.0,>=1.0.7 (from shazamio)
  Using cached shazamio_core-1.0.7.tar.gz (2.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      💥 maturin failed
        Caused by: Can't find /private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-v20bfs9n/shazamio-core_99820c2f6dbb4ca4a69a735798cb5690/Cargo.toml (in /private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-v20bfs9n/shazamio-core_99820c2f6dbb4ca4a69a735798cb5690)
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-modern-metadata-nibupmsw', '--interpreter', '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-modern-metadata-nibupmsw --interpreter /Library/Frameworks/Python.framework/Versions/3.10/bin/python3`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by therc01** [comment]
getting this when doing pip3 install 

WARNING: Discarding https://files.pythonhosted.org/packages/12/16/56f26eb75a5ea0b6b98e46c168fdc31177eae158be0b87fee916774b9a99/mutagen-1.19.tar.gz#sha256=f7c5d9d936dbd15e48c126e17ce868d8454ae2ca8fc666f83caab12833d4a07d (from https://pypi.org/simple/mutagen/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached mutagen-1.18.tar.gz (631 kB)
    ERROR: Command errored out with exit status 1:
     command: '/Users/vangala/Documents/__ALL BEATS/mp3ShazamAutoTag-main 2/venv/bin/python3' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-zcayyvmf/mutagen_5f33a858b654459cb51a819d3d86c962/setup.py'"'"'; __file__='"'"'/private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-zcayyvmf/mutagen_5f33a858b654459cb51a819d3d86c962/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-pip-egg-info-2jmst35i
         cwd: /private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-zcayyvmf/mutagen_5f33a858b654459cb51a819d3d86c962/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qw/h4rml07d7tgg8rk7n74zz7bm0000gn/T/pip-install-zcayyvmf/mutagen_5f33a858b654459cb51a819d3d86c962/setup.py", line 54
        print "Building release tarball."
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
    ----------------------------------------

**Comment by davidAlgis** [comment]
Hello,
Sorry, I've only tested the code on Ubuntu and Windows 11 and I don't have a computer with macOS at my disposal... The problem seems to be more related to the [ShazamIO](https://github.com/shazamio/ShazamIO) package, but I saw that you had already added a problem about it. Don't hesitate if you have an answer or if you've found a solution, to write it here, so I can maybe fix the problem. Good luck in any case!

**Comment by therc01** [comment]
Sure

**Comment by johnsturgeon** [comment]
@therc01 I'm using the library just fine on macOS M1 chip,  but I use `poetry` and not pip to manage my packages.  You might try that.

**Comment by davidAlgis** [comment]
templateK proposed the following solution in this issue https://github.com/shazamio/ShazamIO/issues/112#issuecomment-2357835422 :
> There's no wheel artifact for macosx-x86_64 of `shazamio-core`, so pip is trying to compile from source but there's no `Cargo.toml` in the `shazamio_core-1.0.7.tar.gz` source code tarball.
> 
> I installed `shazamio` with following commands with `python-3.12`.
> 
> ```shell
> git clone https://github.com/shazamio/shazamio-core.git
> cd shazamio-core
> git switch 1.0.7
> python -m pip install .
> pip install shazamio
> ```

**Comment by Rapid1898-code** [comment]
It try to install that on Mac - but when i enter the 3rd statement i get this error

```
(shazamio) PolziMacs-Mini:shazamio-core polzimac$ git switch 1.0.7
fatal: a branch is expected, got tag '1.0.7'
(shazamio) PolziMacs-Mini:shazamio-core polzimac$ 
```
